language: emacs-lisp
sudo: false

env:
  - EMACS_TARGET=emacs-24.4
  - EMACS_TARGET=emacs-24.5
  - EMACS_TARGET=emacs-25.1
  - EMACS_TARGET=emacs-git

before_install:
  - make -f Makefile.travis before_install

install:
  - PATH=~/.cask/bin:$PATH make -f Makefile.travis install

script:
  - emacs --version
  - PATH=~/.cask/bin:$PATH make -f Makefile.travis script

