(require-package 'multi-term)

(setq multi-term-program "/bin/zsh")

(global-set-key (kbd "<f1>") 'multi-term)

(setq term-bind-key-alist
      '(("C-c C-j" . term-line-mode)
        ("C-c C-k" . term-char-mode)
        ("C-c C-p" . multi-term-prev)
        ("C-c C-n" . multi-term-next)
        ("C-c C-c" . term-interrupt-subjob)
        ("C-c C-e" . term-send-esc)
        ("C-p" . previous-line)
        ("C-n" . next-line)
        ("C-s" . isearch-forward)
        ("C-r" . term-send-reverse-search-history)
        ("C-m" . term-send-return)
        ("C-y" . term-paste)
        ("M-f" . term-send-forward-word)
        ("M-b" . term-send-backward-word)
        ("M-o" . term-send-backspace)
        ("M-p" . term-send-up)
        ("M-n" . term-send-down)
        ("M-M" . term-send-forward-kill-word)
        ("M-N" . term-send-backward-kill-word)
        ("<M-backspace>" . term-send-backward-kill-word)
        ("M-r" . term-send-reverse-search-history)
        ("M-," . term-send-raw)
        ("M-." . comint-dynamic-complete)))
(multi-term-keystroke-setup)

(provide 'init-term)
