#!/bin/sh

# Check if bundles have the .git folder removed.
staged_files="$(git diff --cached --name-only --diff-filter=ACM) | grep 'bundle/'"

if test -n "$staged_files"
then
    for file in $staged_files
    do
        if test -d "$file" && test -e "$file/.git"
        then
            echo "You're about to commit another git repository: $file."
            echo "Please use submodules for this functionality or delete the .git directory."
            echo "To bypass this hook, use: git commit --no-verify"
            exit 1
        fi
    done
fi

# Lint staged .lisp and .asd files before commit
# Get list of staged .lisp and .asd files but omit files under bundle/
staged_lisp_files="$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(lisp|asd)$' | grep -v 'bundle/')"

if test -n "$staged_lisp_files"
then
    echo "Running ocicl lint on staged files..."

    if ! ocicl --color never lint $staged_lisp_files
    then
        echo "Linting failed. Please fix the issues before committing."
        echo "To bypass this hook, use: git commit --no-verify"
        exit 1
    fi
fi
